name: first workflow
on:
  push:
    branches:
      - "main"
jobs:
  First-workflow-job:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: bash command
        uses: echo "first workflos"
        shell: bash

      