name: first workflow
on:
  push:
    branches:
      - "main"
jobs:
  First-workflow-job:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: before checkout action
        uses: ls
        shell: bash

      - name: checkout steps
        uses: actions/checkout@v4
        shell: bash

      - name: after checkout action
        uses: ls
        shell: bash